version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    # Critical linters that are available in v2 and enabled by default
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  exclude-rules:
    # Exclude G104 (error handling) for deferred Close calls in test helpers
    - path: _test\.go
      text: "G104"
    - path: internal/infrastructure/eventstore/sqlite\.go
      text: "G104"
      linters:
        - gosec