version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    # Critical linters that are available in v2 and enabled by default
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused