version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    # Critical linters - must pass
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - gci
    - gofmt
    - goimports
    - misspell