coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 5%
        if_no_uploads: error
    patch:
      default:
        target: 80%
        threshold: 10%
        if_no_uploads: error

ignore:
  - "**/*_test.go"
  - "**/test/**"
  - "**/examples/**"
  - "**/cmd/**"
  - "**/vendor/**"
  - "**/*.pb.go"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

github_checks:
  annotations: true