# Traffic Control Configuration Example
version: "1.0"
device: eth0
bandwidth: 1Gbps

# Default settings for all classes
defaults:
  burst_ratio: 1.5    # Maximum bandwidth = guaranteed * 1.5

# Traffic classes hierarchy
classes:
  # Business critical traffic
  - name: business_critical
    guaranteed: 400Mbps
    maximum: 800Mbps
    priority: 1      # High priority
    children:
      - name: voip
        guaranteed: 100Mbps
        maximum: 150Mbps
        priority: 0  # Highest priority
      
      - name: database
        guaranteed: 300Mbps
        maximum: 650Mbps
        priority: 2
        children:
          - name: primary
            guaranteed: 200Mbps
            maximum: 400Mbps
            priority: 2
          
          - name: replica
            guaranteed: 100Mbps
            maximum: 250Mbps
            priority: 2

  # Standard business traffic
  - name: standard
    guaranteed: 300Mbps
    maximum: 600Mbps
    priority: 4
    children:
      - name: web
        guaranteed: 150Mbps
        priority: 3
      
      - name: email
        guaranteed: 100Mbps
        priority: 3
      
      - name: file_transfer
        guaranteed: 50Mbps
        priority: 4

  # Bulk/Background traffic
  - name: bulk
    guaranteed: 200Mbps
    maximum: 400Mbps
    priority: 6      # Low priority
    children:
      - name: backup
        guaranteed: 100Mbps
        maximum: 200Mbps
        priority: 6
      
      - name: updates
        guaranteed: 100Mbps
        maximum: 200Mbps
        priority: 6

  # Guest traffic
  - name: guest
    guaranteed: 100Mbps
    maximum: 200Mbps
    priority: 6      # Low priority

# Traffic matching rules
rules:
  # VoIP traffic
  - name: sip_signaling
    match:
      dest_port: [5060, 5061]
      protocol: udp
    target: business_critical.voip
    priority: 1
  
  - name: rtp_media
    match:
      dest_port: [10000, 10001, 10002, 10003, 10004, 10005, 10006, 10007, 10008, 10009]
      protocol: udp
    target: business_critical.voip
    priority: 1

  # Database traffic
  - name: primary_db
    match:
      destination_ip: 10.0.1.10
      dest_port: [3306, 5432]
    target: business_critical.database.primary
    priority: 2
  
  - name: replica_db
    match:
      destination_ip: 10.0.1.11
      dest_port: [3306, 5432]
    target: business_critical.database.replica
    priority: 2

  # Web traffic
  - name: http_traffic
    match:
      dest_port: [80, 443]
    target: standard.web
    priority: 3

  # Email traffic
  - name: smtp
    match:
      dest_port: [25, 587, 465]
    target: standard.email
    priority: 3
  
  - name: imap_pop
    match:
      dest_port: [143, 993, 110, 995]
    target: standard.email
    priority: 3

  # Backup traffic
  - name: backup_traffic
    match:
      source_ip: 10.0.2.0/24
      dest_port: [873]  # rsync
    target: bulk.backup
    priority: 5

  # Guest network
  - name: guest_network
    match:
      source_ip: 192.168.100.0/24
    target: guest
    priority: 10