name: Auto Tag on Main

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create date-based tag and release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Generate date-based tag with time
          TAG_NAME="v$(date +%Y%m%d%H%M%S)"
          
          # Create and push tag
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git tag -a "$TAG_NAME" -m "Release $TAG_NAME"
          git push origin "$TAG_NAME"
          
          echo "Created tag: $TAG_NAME"
          
          # Create release
          gh release create "$TAG_NAME" \
            --title "Release $TAG_NAME" \
            --notes "Automated release for Traffic Control Go Library" \
            --latest