name: Build and Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

permissions:
  contents: write

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-build-
          
    - name: Download dependencies
      run: go mod download
      
    - name: Build CLI tool for multiple platforms
      run: |
        # Create bin directory
        mkdir -p bin
        
        # Linux amd64
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin/tcctl-linux-amd64 ./cmd/tcctl
        
        # Linux arm64
        GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o bin/tcctl-linux-arm64 ./cmd/tcctl
        
        # macOS amd64
        GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o bin/tcctl-darwin-amd64 ./cmd/tcctl
        
        # macOS arm64 (Apple Silicon)
        GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o bin/tcctl-darwin-arm64 ./cmd/tcctl
        
        # Windows amd64
        GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o bin/tcctl-windows-amd64.exe ./cmd/tcctl
        
    - name: Build examples
      run: |
        go build -o bin/basic-demo ./examples/basic_demo.go
        go build -o bin/priority-demo ./examples/priority_demo.go
        
    - name: Create checksums
      run: |
        cd bin
        sha256sum * > checksums.txt
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: bin/
        retention-days: 30
        
  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: binaries
        path: bin/
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: bin/*
        generate_release_notes: true
        draft: false
        prerelease: ${{ contains(github.ref, '-') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}