name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  GO_VERSION_DEFAULT: '1.23'
  GO_VERSION_MIN: '1.21'

jobs:
  test:
    strategy:
      matrix:
        go-version: ['1.21', '1.22', '1.23']
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Run tests
      run: make test

    - name: Run linter
      if: matrix.platform == 'ubuntu-latest' && matrix.go-version == '1.23'
      run: |
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        make lint

    - name: Run security scanner
      if: matrix.platform == 'ubuntu-latest' && matrix.go-version == '1.23'
      run: |
        go install github.com/securego/gosec/v2/cmd/gosec@latest
        make security

    - name: Test build
      run: make build
      
    - name: Install iperf3 for integration tests
      if: matrix.platform == 'ubuntu-latest' && matrix.go-version == '1.23'
      run: |
        sudo apt-get update
        sudo apt-get install -y iperf3 iproute2
        
    - name: Run integration tests
      if: matrix.platform == 'ubuntu-latest' && matrix.go-version == '1.23'
      run: |
        sudo -E env "PATH=$PATH" go test -v -tags=integration -run TestTrafficControlWithIperf3 ./test/integration/... -count=1 || true

  goreleaser-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION_DEFAULT }}

    - name: Check GoReleaser config
      uses: goreleaser/goreleaser-action@v5
      with:
        distribution: goreleaser
        version: latest
        args: check

    - name: Build snapshot
      uses: goreleaser/goreleaser-action@v5
      with:
        distribution: goreleaser
        version: latest
        args: build --snapshot --clean