name: Integration Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch: # Allow manual triggering

env:
  GO_VERSION_DEFAULT: '1.23'

permissions:
  contents: read

jobs:
  integration-test:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION_DEFAULT }}
        
    - name: Install iperf3
      run: |
        sudo apt-get update
        sudo apt-get install -y iperf3 iproute2
        iperf3 --version
        
    - name: Verify kernel TC support
      run: |
        # Check if tc is available
        which tc
        # Check kernel modules
        lsmod | grep -E "sch_|cls_" || true
        
    - name: Run integration tests
      run: |
        # GitHub Actions runners have passwordless sudo
        # Run tests with sudo as they need root for TC operations
        sudo -E env "PATH=$PATH" "HOME=$HOME" go test -v -tags=integration ./test/integration/... -count=1 -timeout 10m
      
    - name: Upload test logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: integration-test-logs
        path: |
          /tmp/tc-test-*.log
          
    - name: Show TC state after tests
      if: always()
      run: |
        echo "=== TC Qdisc State ==="
        sudo tc qdisc show || true
        echo "=== TC Class State ==="
        sudo tc class show || true
        echo "=== TC Filter State ==="
        sudo tc filter show || true