name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      # Use the default GITHUB_TOKEN which has permissions based on the workflow permissions
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: go
          token: ${{ secrets.GITHUB_TOKEN }}
          skip-labeling: true
          
  # Build and upload release artifacts when a release is created
  build-release:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        
    - name: Build CLI tool for multiple platforms
      run: |
        # Create bin directory
        mkdir -p bin
        
        # Build version with tag
        VERSION=${{ needs.release-please.outputs.tag_name }}
        
        # Linux amd64
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w -X main.version=${VERSION}" -o bin/tcctl-linux-amd64 ./cmd/tcctl
        
        # Linux arm64
        GOOS=linux GOARCH=arm64 go build -ldflags="-s -w -X main.version=${VERSION}" -o bin/tcctl-linux-arm64 ./cmd/tcctl
        
        # macOS amd64
        GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w -X main.version=${VERSION}" -o bin/tcctl-darwin-amd64 ./cmd/tcctl
        
        # macOS arm64 (Apple Silicon)
        GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w -X main.version=${VERSION}" -o bin/tcctl-darwin-arm64 ./cmd/tcctl
        
        # Windows amd64
        GOOS=windows GOARCH=amd64 go build -ldflags="-s -w -X main.version=${VERSION}" -o bin/tcctl-windows-amd64.exe ./cmd/tcctl
        
    - name: Build examples
      run: |
        go build -o bin/basic-demo ./examples/basic_demo.go
        go build -o bin/priority-demo ./examples/priority_demo.go
        
    - name: Create checksums
      run: |
        cd bin
        sha256sum * > checksums.txt
        
    - name: Upload Release Artifacts
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload ${{ needs.release-please.outputs.tag_name }} bin/* --clobber